task_managment/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name ='accounts'
urlpatterns = [
    path('', views.home_login, name='home_login_path'),
    path('welcomeback/', views.welcomeback, name='welcome_back_path'),
    path('register/', views.register, name='register_path'),
    path('login/', LoginView.as_view(), name='login_path'),
    path('logout/', LogoutView.as_view(next_page='accounts:home_login_path') ,name='logout_path'),

]

task_managment/app_task_manager/urls.py
from django.urls import path
from . import views

app_name = 'app_task_manager'
urlpatterns = [
    path('', views.home, name='home_path'),
    path('delete/<list_id>',views.delete, name='delete'),

]

task_managment/task_managment/urls.py
from django.contrib import admin
from django.urls import path, include
from app_task_manager import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_task_manager.urls', namespace='app_task_manager')),
    path('accounts/', include('accounts.urls'))
]

task_managment/accounts/models.py
from django.db import models

# Create your models here.

task_managment/app_task_manager/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class taskModel(models.Model):
    task_name = models.CharField(max_length=30)
    priority_level = models.CharField(max_length=30)
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "%s %s"%(self.task_name, self.completed)

task_managment/app_task_manager/forms.py
from django import forms
from .models import taskModel

class taskForm(forms.ModelForm):
    class Meta:
        model = taskModel
        fields = ['task_name','priority_level']

task_managment/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

def home_login(request):
    return render(request, 'loginpage.html')

@login_required
def welcomeback(request):
    return render(request, 'welcomeback.html')
# Create your views here.

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login_path')
    else :
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form':form})

task_managment/app_task_manager/views.py
from django.shortcuts import render, redirect
from .models import taskModel
from .forms import taskForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

@login_required
def home(request):

    if request.method == 'POST':
        form = taskForm(request.POST or None)
        if form.is_valid():
            print('form valid')
            form.save()
            all_items = taskModel.objects.all()
            messages.success(request, ("New item addedd.."))
            print(all_items)
            return render(request, 'index.html', {'all_items': all_items})
        else :
            print('invalid form')
            return render(request, 'index.html', {'all_items': 'Not valid form'})
    else:
        all_items = taskModel.objects.all()
        return render(request, 'index.html', {'all_items': all_items})

def delete(request, list_id):

    item = taskModel.objects.get(pk=list_id)
    item.delete()
    messages.success(request, ('Item deleted'))
    return redirect('home_path')

task_managment/accounts/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>TaskManager</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
  {% include 'navbar_base.html' %}
  {% block body_block %}

  {% endblock%}
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>


</body>
</html>

task_managment/accounts/templates/loginpage.html
{% extends 'base.html' %}

{% block body_block %}

<h4>Log in</h4>
<h3>Inser your name</h3>
{% endblock %}

task_managment/accounts/templates/navbar_base.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">TaskManager</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <div class="collapse navbar-collapse justify-content-between">

    </div>
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'app_task_manager:home_path' %}">Home</a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:logout_path' %}">Log out</a>
        </li>
      {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:register_path' %}">Register</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:login_path' %}">Log in</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

task_managment/accounts/templates/welcomeback.html
{% extends 'base.html' %}
{% block body_block  %}
  <h2>Welcome, {{user.username }}</h2>
  <h5>Let's manage some tasks</h5>
{% endblock %}

task_managment/app_task_manager/templates/base_task_manager.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>TaskManager</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">TaskManager</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'app_task_manager:home_path' %}">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:register_path' %}">Register</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:login_path' %}">Log in</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:logout_path' %}">Log out</a>
      </li>
    </ul>
  </div>
</nav>
{% block body_task_block %}
{% endblock%}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>


</body>
</html>

task_managment/app_task_manager/templates/index.html
{% extends 'base_task_manager.html' %}

{% block body_task_block %}
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>TaskManager</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>

<body>
  <h2>Your task list:</h2>
  <br>
  <br>
  <table class="table table-dark table-hover table-striped-columns">
    <tr>
      <th>Task Name</th>
      <th>priority</th>
      <th>Completed</th>
      <th>Delete</th>
    </tr>
    {%for item in all_items%}
    <tr>
      <td>{{item.task_name}}</td>
      <td>{{item.priority_level}}</td>
      <td>{{item.completed}}</td>
      <td><a href="{% url 'app_task_manager:delete' item.id%}">Delete Me</a></td>
    </tr>
    <p></p>
    {%endfor%}
  </table><br>

  <form action="{% url 'app_task_manager:home_path' %}" method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="task_name" class="form-label">Task</label><br>
      <input type="text" class="form-text" name="task_name" placeholder="Enter task"><br>
    </div>

    <div class="mb-3">
      <label for="priority_level" class="form-label">Priority</label><br>
      <input type="text" class="form-text" name="priority_level" placeholder="Enter priority"><br>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>


  </form>
{% endblock %}